- name: generate docs
  hosts: localhost
  connection: local
  vars:
    operator_version: "{{ lookup('env','VERSION') | default('0.0.1', true) }}"
    docs_path: "{{ playbook_dir }}/../docs/"
    readme_path: "{{ docs_path }}/README.md"
  tasks:
    - name: create docs folder
      file:
        path: "{{ docs_path }}"
        state: directory
        mode: '0755'

    - name: generate docs main readme
      template:
        src: README.md.j2
        dest: "{{ readme_path }}"
        mode: '0644'
