# permissions for end users to view moodles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: moodle-operator
    app.kubernetes.io/managed-by: kustomize
  name: moodle-viewer-role
rules:
- apiGroups:
  - m4e.krestomat.io
  resources:
  - moodles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - m4e.krestomat.io
  resources:
  - moodles/status
  verbs:
  - get
