# permissions for end users to edit routines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: routine-editor-role
rules:
- apiGroups:
  - m4e.krestomat.io
  resources:
  - routines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - m4e.krestomat.io
  resources:
  - routines/status
  verbs:
  - get
