# permissions for end users to edit routines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: routine-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: moodle-operator
    app.kubernetes.io/part-of: moodle-operator
    app.kubernetes.io/managed-by: kustomize
  name: routine-editor-role
rules:
- apiGroups:
  - m4e.krestomat.io
  resources:
  - routines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - m4e.krestomat.io
  resources:
  - routines/status
  verbs:
  - get
