# permissions for end users to view routines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: moodle-operator
    app.kubernetes.io/managed-by: kustomize
  name: routine-viewer-role
rules:
- apiGroups:
  - m4e.krestomat.io
  resources:
  - routines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - m4e.krestomat.io
  resources:
  - routines/status
  verbs:
  - get
