apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: moodle-test
namePrefix: moodle-
resources:
- ../crd
- ../rbac
- ../manager
patchesStrategicMerge:
- manager_image.yaml
- debug_logs_patch.yaml
- watch_namespace_patch.yaml
- ../default/manager_auth_proxy_patch.yaml
- ../manager/profile_tasks_patch.yaml
images:
- name: testing
  newName: testing-operator
patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --zap-devel=true
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --zap-time-encoding=iso8601
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --zap-encoder=console
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --ansible-args='-D'
  target:
    kind: Deployment
