---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - community.kubernetes

  tasks:
    - import_tasks: kustomize-prepare.yml

    - name: Remove the m4e.krestomat.io/v1alpha1.M4e
      when: lookup('k8s', api_version='apiextensions.k8s.io/v1', kind='CustomResourceDefinition', resource_name='m4es.m4e.krestomat.io')
      k8s:
        state: absent
        namespace: '{{ namespace }}'
        definition: "{{ lookup('template', '/'.join([samples_dir, cr_file])) | from_yaml }}"
        wait: true

    - import_tasks: kustomize.yml
      vars:
        state: absent

    - name: Unset pull policy
      command: '{{ kustomize }} edit remove patch --path pull_policy/{{ operator_pull_policy }}.yaml'
      args:
        chdir: '{{ config_dir }}/testing'

    - name: Unset testing image
      command: '{{ kustomize }} edit set image testing=testing-operator'
      args:
        chdir: '{{ config_dir }}/testing'

    - name: Unset testing namespace
      command: '{{ kustomize }} edit set namespace m4e-test'
      args:
        chdir: '{{ config_dir }}/testing'

    - name: Unset testing nameprefix
      command: '{{ kustomize }} edit set nameprefix m4e-'
      args:
        chdir: '{{ config_dir }}/testing'
