---
dependency:
  name: galaxy
driver:
  name: delegated
lint: |
  set -e
  yamllint -d "{extends: relaxed, rules: {line-length: {max: 120}}}" .
  if [ -d roles ]; then
    yamllint roles/*
    ansible-lint roles/*
    flake8 roles/*
  fi
platforms:
  - name: cluster
    groups:
      - k8s
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        namespace: "{{ lookup('env', 'TEST_OPERATOR_NAMESPACE') | default('m4e-test',true) }}"
        nameprefix: "{{ lookup('env', 'TEST_OPERATOR_NAMEPREFIX') | default('m4e-',true) }}"
        omit_crds_deletion: "{{ lookup('env', 'TEST_OPERATOR_OMIT_CRDS_DELETION') | default(false,true) | bool }}"
    host_vars:
      localhost:
        ansible_python_interpreter: '{{ ansible_playbook_python }}'
        config_dir: ${MOLECULE_PROJECT_DIRECTORY}/config
        samples_dir: ${MOLECULE_PROJECT_DIRECTORY}/config/samples
        cr_file: ${CR_FILE:-"m4e_v1alpha1_m4e.yaml"}
        operator_image: "{{ lookup('env', 'OPERATOR_IMAGE') | default('',true) }}"
        operator_pull_policy: ${OPERATOR_PULL_POLICY:-"Always"}
        kustomize: ${KUSTOMIZE_PATH:-kustomize}
