- name: nginx resources for moodle
  hosts: localhost
  gather_facts: false
  collections:
    - kubernetes.core
    - operator_sdk.util
  tasks:
    - name: import nginx role
      import_role:
        name: krestomatio.k8s.v1alpha1.m4e.nginx
