- name: moodle routine status
  hosts: localhost
  gather_facts: false
  collections:
    - kubernetes.core
    - operator_sdk.util
  tasks:
    - name: import moodle routine status
      import_role:
        name: krestomatio.k8s.v1alpha1.m4e.routine
        tasks_from: status.yml

- name: moodle routine
  hosts: "{{ routine_pods_ready_group | default('') }}:&{{ routine_moodle_container_group | default('') }}"
  gather_facts: false
  collections:
    - kubernetes.core
    - operator_sdk.util
  tasks:
    - name: import moodle routine
      import_role:
        name: krestomatio.k8s.v1alpha1.m4e.routine
