apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
      - name: release
        resources: {}
        taskSpec:
          metadata: {}
          stepTemplate:
            name: ''
            env:
              - name: HOME
                value: /tekton/home
              - name: VERSION_MAKEFILE
                value: "true"
              - name: PROJECT_TIMESTAMP
                value: midnight
            resources:
              requests:
                cpu: 400m
                memory: 512Mi
            workingDir: /workspace/source
          steps:
            - image: uses:krestomatio/jx3-pipeline-catalog/tasks/git-clone/git-clone.yaml@25de7882a54f869732075eb46b04203ada8926c5
            - image: ghcr.io/jenkins-x/jx-changelog:0.0.47
              name: changelog
              args:
              - changelog
              command:
              - make
            - image: quay.io/krestomatio/ansible-operator-ci
              name: release
              args:
              - release
              command:
              - make
            - image: quay.io/krestomatio/ansible-operator-ci
              name: promote
              args:
              - promote
              command:
              - make
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
