apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
      - name: release
        resources: {}
        taskSpec:
          metadata: {}
          stepTemplate:
            name: ''
            env:
              - name: HOME
                value: /tekton/home
              - name: VERSION_MAKEFILE
                value: "true"
              - name: PROJECT_TIMESTAMP
                value: midnight
            resources:
              limits:
                cpu: 400m
                memory: 512Mi
              requests:
                cpu: 50m
                memory: 32Mi
            workingDir: /workspace/source
          steps:
            - image: uses:krestomatio/jx3-pipeline-catalog/tasks/git-clone/git-clone.yaml@7280afe8d12539b956237d6351059eda3e2118a7
            - image: ghcr.io/jenkins-x/jx-changelog:0.0.47
              name: changelog
              resources: {}
              args:
              - changelog
              command:
              - make
            - image: quay.io/krestomatio/ansible-operator-ci
              name: release
              args:
              - release
              command:
              - make
              resources:
                requests:
                  cpu: 0.1
                  memory: 128Mi
            - image: quay.io/krestomatio/ansible-operator-ci
              name: promote
              resources: {}
              args:
              - promote
              command:
              - make
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
